apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: external-secrets-store # -- Provide secret store name
  namespace: kube-system # -- Do not change this namespace name
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1 # -- Provoide your cluster region
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa # -- Do not change this name field